/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class AEng2Floatingpoint extends PFloatingpoint
{
    private TUnoeng _unoeng_;
    private PIntnum _intnum_;

    public AEng2Floatingpoint()
    {
        // Constructor
    }

    public AEng2Floatingpoint(
        @SuppressWarnings("hiding") TUnoeng _unoeng_,
        @SuppressWarnings("hiding") PIntnum _intnum_)
    {
        // Constructor
        setUnoeng(_unoeng_);

        setIntnum(_intnum_);

    }

    @Override
    public Object clone()
    {
        return new AEng2Floatingpoint(
            cloneNode(this._unoeng_),
            cloneNode(this._intnum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEng2Floatingpoint(this);
    }

    public TUnoeng getUnoeng()
    {
        return this._unoeng_;
    }

    public void setUnoeng(TUnoeng node)
    {
        if(this._unoeng_ != null)
        {
            this._unoeng_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unoeng_ = node;
    }

    public PIntnum getIntnum()
    {
        return this._intnum_;
    }

    public void setIntnum(PIntnum node)
    {
        if(this._intnum_ != null)
        {
            this._intnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intnum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unoeng_)
            + toString(this._intnum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unoeng_ == child)
        {
            this._unoeng_ = null;
            return;
        }

        if(this._intnum_ == child)
        {
            this._intnum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unoeng_ == oldChild)
        {
            setUnoeng((TUnoeng) newChild);
            return;
        }

        if(this._intnum_ == oldChild)
        {
            setIntnum((PIntnum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
