/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class AEngFloatingpoint extends PFloatingpoint
{
    private PFixedpoint _fixedpoint_;
    private TEng _eng_;
    private PIntnum _intnum_;

    public AEngFloatingpoint()
    {
        // Constructor
    }

    public AEngFloatingpoint(
        @SuppressWarnings("hiding") PFixedpoint _fixedpoint_,
        @SuppressWarnings("hiding") TEng _eng_,
        @SuppressWarnings("hiding") PIntnum _intnum_)
    {
        // Constructor
        setFixedpoint(_fixedpoint_);

        setEng(_eng_);

        setIntnum(_intnum_);

    }

    @Override
    public Object clone()
    {
        return new AEngFloatingpoint(
            cloneNode(this._fixedpoint_),
            cloneNode(this._eng_),
            cloneNode(this._intnum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEngFloatingpoint(this);
    }

    public PFixedpoint getFixedpoint()
    {
        return this._fixedpoint_;
    }

    public void setFixedpoint(PFixedpoint node)
    {
        if(this._fixedpoint_ != null)
        {
            this._fixedpoint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fixedpoint_ = node;
    }

    public TEng getEng()
    {
        return this._eng_;
    }

    public void setEng(TEng node)
    {
        if(this._eng_ != null)
        {
            this._eng_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eng_ = node;
    }

    public PIntnum getIntnum()
    {
        return this._intnum_;
    }

    public void setIntnum(PIntnum node)
    {
        if(this._intnum_ != null)
        {
            this._intnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intnum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fixedpoint_)
            + toString(this._eng_)
            + toString(this._intnum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fixedpoint_ == child)
        {
            this._fixedpoint_ = null;
            return;
        }

        if(this._eng_ == child)
        {
            this._eng_ = null;
            return;
        }

        if(this._intnum_ == child)
        {
            this._intnum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fixedpoint_ == oldChild)
        {
            setFixedpoint((PFixedpoint) newChild);
            return;
        }

        if(this._eng_ == oldChild)
        {
            setEng((TEng) newChild);
            return;
        }

        if(this._intnum_ == oldChild)
        {
            setIntnum((PIntnum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
