/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class AIntFixedpoint extends PFixedpoint
{
    private PIntnum _intnum_;

    public AIntFixedpoint()
    {
        // Constructor
    }

    public AIntFixedpoint(
        @SuppressWarnings("hiding") PIntnum _intnum_)
    {
        // Constructor
        setIntnum(_intnum_);

    }

    @Override
    public Object clone()
    {
        return new AIntFixedpoint(
            cloneNode(this._intnum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntFixedpoint(this);
    }

    public PIntnum getIntnum()
    {
        return this._intnum_;
    }

    public void setIntnum(PIntnum node)
    {
        if(this._intnum_ != null)
        {
            this._intnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intnum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intnum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intnum_ == child)
        {
            this._intnum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intnum_ == oldChild)
        {
            setIntnum((PIntnum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
