/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class AListSbody extends PSbody
{
    private PCname _cname_;
    private TComma _comma_;
    private PSbody _sbody_;

    public AListSbody()
    {
        // Constructor
    }

    public AListSbody(
        @SuppressWarnings("hiding") PCname _cname_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSbody _sbody_)
    {
        // Constructor
        setCname(_cname_);

        setComma(_comma_);

        setSbody(_sbody_);

    }

    @Override
    public Object clone()
    {
        return new AListSbody(
            cloneNode(this._cname_),
            cloneNode(this._comma_),
            cloneNode(this._sbody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListSbody(this);
    }

    public PCname getCname()
    {
        return this._cname_;
    }

    public void setCname(PCname node)
    {
        if(this._cname_ != null)
        {
            this._cname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cname_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSbody getSbody()
    {
        return this._sbody_;
    }

    public void setSbody(PSbody node)
    {
        if(this._sbody_ != null)
        {
            this._sbody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sbody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cname_)
            + toString(this._comma_)
            + toString(this._sbody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cname_ == child)
        {
            this._cname_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._sbody_ == child)
        {
            this._sbody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cname_ == oldChild)
        {
            setCname((PCname) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._sbody_ == oldChild)
        {
            setSbody((PSbody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
