/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleRedundancy extends PRedundancy
{
    private TRedundancyKw _redundancyKw_;
    private PAbsnum _absnum_;
    private TSemi _semi_;

    public ASimpleRedundancy()
    {
        // Constructor
    }

    public ASimpleRedundancy(
        @SuppressWarnings("hiding") TRedundancyKw _redundancyKw_,
        @SuppressWarnings("hiding") PAbsnum _absnum_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setRedundancyKw(_redundancyKw_);

        setAbsnum(_absnum_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleRedundancy(
            cloneNode(this._redundancyKw_),
            cloneNode(this._absnum_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleRedundancy(this);
    }

    public TRedundancyKw getRedundancyKw()
    {
        return this._redundancyKw_;
    }

    public void setRedundancyKw(TRedundancyKw node)
    {
        if(this._redundancyKw_ != null)
        {
            this._redundancyKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._redundancyKw_ = node;
    }

    public PAbsnum getAbsnum()
    {
        return this._absnum_;
    }

    public void setAbsnum(PAbsnum node)
    {
        if(this._absnum_ != null)
        {
            this._absnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._absnum_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._redundancyKw_)
            + toString(this._absnum_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._redundancyKw_ == child)
        {
            this._redundancyKw_ = null;
            return;
        }

        if(this._absnum_ == child)
        {
            this._absnum_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._redundancyKw_ == oldChild)
        {
            setRedundancyKw((TRedundancyKw) newChild);
            return;
        }

        if(this._absnum_ == oldChild)
        {
            setAbsnum((PAbsnum) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
