/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TDescrKw extends Token
{
    public TDescrKw()
    {
        super.setText("description");
    }

    public TDescrKw(int line, int pos)
    {
        super.setText("description");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDescrKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDescrKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDescrKw text.");
    }
}
