/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TImplKw extends Token
{
    public TImplKw()
    {
        super.setText("implementedBy");
    }

    public TImplKw(int line, int pos)
    {
        super.setText("implementedBy");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImplKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImplKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImplKw text.");
    }
}
