/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TNodetecKw extends Token
{
    public TNodetecKw()
    {
        super.setText("nodetects");
    }

    public TNodetecKw(int line, int pos)
    {
        super.setText("nodetects");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNodetecKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNodetecKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNodetecKw text.");
    }
}
