/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TNouseKw extends Token
{
    public TNouseKw()
    {
        super.setText("nouses");
    }

    public TNouseKw(int line, int pos)
    {
        super.setText("nouses");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNouseKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNouseKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNouseKw text.");
    }
}
