/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TServKw extends Token
{
    public TServKw()
    {
        super.setText("service");
    }

    public TServKw(int line, int pos)
    {
        super.setText("service");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TServKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTServKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TServKw text.");
    }
}
