/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.node;

import org.wnl.textual.analysis.*;

@SuppressWarnings("nls")
public final class TUnoeng extends Token
{
    public TUnoeng()
    {
        super.setText("1E");
    }

    public TUnoeng(int line, int pos)
    {
        super.setText("1E");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnoeng(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnoeng(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnoeng text.");
    }
}
