/* This file was generated by SableCC (http://www.sablecc.org/). */

package bn.analysis.distribution.node;

import bn.analysis.distribution.analysis.Analysis;

@SuppressWarnings("nls")
public final class AListStructures extends PStructures
{
    private PStructure _structure_;
    private PStructures _structures_;

    public AListStructures()
    {
        // Constructor
    }

    public AListStructures(
        @SuppressWarnings("hiding") PStructure _structure_,
        @SuppressWarnings("hiding") PStructures _structures_)
    {
        // Constructor
        setStructure(_structure_);

        setStructures(_structures_);

    }

    @Override
    public Object clone()
    {
        return new AListStructures(
            cloneNode(this._structure_),
            cloneNode(this._structures_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListStructures(this);
    }

    public PStructure getStructure()
    {
        return this._structure_;
    }

    public void setStructure(PStructure node)
    {
        if(this._structure_ != null)
        {
            this._structure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structure_ = node;
    }

    public PStructures getStructures()
    {
        return this._structures_;
    }

    public void setStructures(PStructures node)
    {
        if(this._structures_ != null)
        {
            this._structures_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structures_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._structure_)
            + toString(this._structures_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._structure_ == child)
        {
            this._structure_ = null;
            return;
        }

        if(this._structures_ == child)
        {
            this._structures_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._structure_ == oldChild)
        {
            setStructure((PStructure) newChild);
            return;
        }

        if(this._structures_ == oldChild)
        {
            setStructures((PStructures) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
