/* This file was generated by SableCC (http://www.sablecc.org/). */

package bn.analysis.distribution.node;

import bn.analysis.distribution.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASimpleStructures extends PStructures
{
    private PStructure _structure_;

    public ASimpleStructures()
    {
        // Constructor
    }

    public ASimpleStructures(
        @SuppressWarnings("hiding") PStructure _structure_)
    {
        // Constructor
        setStructure(_structure_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStructures(
            cloneNode(this._structure_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStructures(this);
    }

    public PStructure getStructure()
    {
        return this._structure_;
    }

    public void setStructure(PStructure node)
    {
        if(this._structure_ != null)
        {
            this._structure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structure_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._structure_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._structure_ == child)
        {
            this._structure_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._structure_ == oldChild)
        {
            setStructure((PStructure) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
