/* This file was generated by SableCC (http://www.sablecc.org/). */

package bn.analysis.distribution.node;

import bn.analysis.distribution.analysis.Analysis;

@SuppressWarnings("nls")
public final class TP extends Token
{
    public TP()
    {
        super.setText("p(");
    }

    public TP(int line, int pos)
    {
        super.setText("p(");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TP(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTP(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TP text.");
    }
}
