/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class AListAttacks extends PAttacks
{
    private PAttacks _attacks_;
    private PAttack _attack_;

    public AListAttacks()
    {
        // Constructor
    }

    public AListAttacks(
        @SuppressWarnings("hiding") PAttacks _attacks_,
        @SuppressWarnings("hiding") PAttack _attack_)
    {
        // Constructor
        setAttacks(_attacks_);

        setAttack(_attack_);

    }

    @Override
    public Object clone()
    {
        return new AListAttacks(
            cloneNode(this._attacks_),
            cloneNode(this._attack_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListAttacks(this);
    }

    public PAttacks getAttacks()
    {
        return this._attacks_;
    }

    public void setAttacks(PAttacks node)
    {
        if(this._attacks_ != null)
        {
            this._attacks_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attacks_ = node;
    }

    public PAttack getAttack()
    {
        return this._attack_;
    }

    public void setAttack(PAttack node)
    {
        if(this._attack_ != null)
        {
            this._attack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attack_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attacks_)
            + toString(this._attack_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attacks_ == child)
        {
            this._attacks_ = null;
            return;
        }

        if(this._attack_ == child)
        {
            this._attack_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attacks_ == oldChild)
        {
            setAttacks((PAttacks) newChild);
            return;
        }

        if(this._attack_ == oldChild)
        {
            setAttack((PAttack) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
