/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANoneUses extends PUses
{
    private TNouseKw _nouseKw_;
    private TSemi _semi_;

    public ANoneUses()
    {
        // Constructor
    }

    public ANoneUses(
        @SuppressWarnings("hiding") TNouseKw _nouseKw_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setNouseKw(_nouseKw_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new ANoneUses(
            cloneNode(this._nouseKw_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoneUses(this);
    }

    public TNouseKw getNouseKw()
    {
        return this._nouseKw_;
    }

    public void setNouseKw(TNouseKw node)
    {
        if(this._nouseKw_ != null)
        {
            this._nouseKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nouseKw_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nouseKw_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nouseKw_ == child)
        {
            this._nouseKw_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nouseKw_ == oldChild)
        {
            setNouseKw((TNouseKw) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
