/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class APlainFloatingpoint extends PFloatingpoint
{
    private PFixedpoint _fixedpoint_;

    public APlainFloatingpoint()
    {
        // Constructor
    }

    public APlainFloatingpoint(
        @SuppressWarnings("hiding") PFixedpoint _fixedpoint_)
    {
        // Constructor
        setFixedpoint(_fixedpoint_);

    }

    @Override
    public Object clone()
    {
        return new APlainFloatingpoint(
            cloneNode(this._fixedpoint_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlainFloatingpoint(this);
    }

    public PFixedpoint getFixedpoint()
    {
        return this._fixedpoint_;
    }

    public void setFixedpoint(PFixedpoint node)
    {
        if(this._fixedpoint_ != null)
        {
            this._fixedpoint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fixedpoint_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fixedpoint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fixedpoint_ == child)
        {
            this._fixedpoint_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fixedpoint_ == oldChild)
        {
            setFixedpoint((PFixedpoint) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
