/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASimpleUses extends PUses
{
    private TUseKw _useKw_;
    private PUbody _ubody_;
    private TSemi _semi_;

    public ASimpleUses()
    {
        // Constructor
    }

    public ASimpleUses(
        @SuppressWarnings("hiding") TUseKw _useKw_,
        @SuppressWarnings("hiding") PUbody _ubody_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setUseKw(_useKw_);

        setUbody(_ubody_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleUses(
            cloneNode(this._useKw_),
            cloneNode(this._ubody_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleUses(this);
    }

    public TUseKw getUseKw()
    {
        return this._useKw_;
    }

    public void setUseKw(TUseKw node)
    {
        if(this._useKw_ != null)
        {
            this._useKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._useKw_ = node;
    }

    public PUbody getUbody()
    {
        return this._ubody_;
    }

    public void setUbody(PUbody node)
    {
        if(this._ubody_ != null)
        {
            this._ubody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ubody_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._useKw_)
            + toString(this._ubody_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._useKw_ == child)
        {
            this._useKw_ = null;
            return;
        }

        if(this._ubody_ == child)
        {
            this._ubody_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._useKw_ == oldChild)
        {
            setUseKw((TUseKw) newChild);
            return;
        }

        if(this._ubody_ == oldChild)
        {
            setUbody((PUbody) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
