/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class TAonKw extends Token
{
    public TAonKw()
    {
        super.setText("affecting");
    }

    public TAonKw(int line, int pos)
    {
        super.setText("affecting");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAonKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAonKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAonKw text.");
    }
}
