/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class TEng extends Token
{
    public TEng()
    {
        super.setText("E");
    }

    public TEng(int line, int pos)
    {
        super.setText("E");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEng(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEng(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEng text.");
    }
}
