/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class TFailureKw extends Token
{
    public TFailureKw()
    {
        super.setText("failure");
    }

    public TFailureKw(int line, int pos)
    {
        super.setText("failure");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFailureKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFailureKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFailureKw text.");
    }
}
