/* This file was generated by SableCC (http://www.sablecc.org/). */

package wnl.textual.node;

import wnl.textual.analysis.Analysis;

@SuppressWarnings("nls")
public final class TReplicationKw extends Token
{
    public TReplicationKw()
    {
        super.setText("replication");
    }

    public TReplicationKw(int line, int pos)
    {
        super.setText("replication");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReplicationKw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReplicationKw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReplicationKw text.");
    }
}
