/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.wnl.textual.lexer;

import java.io.*;
import org.wnl.textual.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNodetecKw(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDetecKw(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImplKw(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAonKw(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNouseKw(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUseKw(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAttackKw(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TServKw(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCompKw(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDescrKw(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFailureKw(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRedundancyKw(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReplicationKw(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSuccessKw(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOCurl(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCCurl(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEng(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnoeng(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpaces(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpace(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TText(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCtrlZ(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {11, 11, 3}, {13, 13, 4}, {26, 26, 5}, {32, 32, 6}, {34, 34, 7}, {44, 44, 8}, {45, 45, 9}, {46, 46, 10}, {48, 48, 11}, {49, 49, 12}, {50, 57, 11}, {59, 59, 13}, {65, 68, 14}, {69, 69, 15}, {70, 90, 14}, {92, 92, 16}, {97, 97, 17}, {98, 98, 14}, {99, 99, 18}, {100, 100, 19}, {101, 101, 14}, {102, 102, 20}, {103, 104, 14}, {105, 105, 21}, {106, 109, 14}, {110, 110, 22}, {111, 113, 14}, {114, 114, 23}, {115, 115, 24}, {116, 116, 14}, {117, 117, 25}, {118, 122, 14}, {123, 123, 26}, {125, 125, 27}, },
            {{9, 13, -2}, {32, 32, 28}, {92, 92, 16}, },
            {{9, 11, -2}, {13, 13, 29}, {32, 92, -3}, },
            {{9, 9, 30}, {10, 10, 31}, {11, 11, 3}, {13, 13, 32}, },
            {{9, 9, 30}, {10, 10, 33}, {11, 13, -5}, },
            {},
            {{9, 9, 34}, {10, 10, 35}, {13, 13, 36}, {32, 32, 6}, {92, 92, 16}, },
            {{32, 32, 37}, {34, 34, 38}, {48, 57, 39}, {65, 90, 40}, {95, 95, 40}, {97, 122, 40}, },
            {},
            {},
            {},
            {{48, 57, 11}, },
            {{48, 57, 11}, {69, 69, 41}, },
            {},
            {{48, 57, 42}, {65, 90, 43}, {95, 95, 43}, {97, 122, 43}, },
            {{48, 122, -16}, },
            {{114, 114, 44}, {116, 116, 45}, },
            {{48, 95, -16}, {97, 101, 43}, {102, 102, 46}, {103, 115, 43}, {116, 116, 47}, {117, 122, 43}, },
            {{48, 95, -16}, {97, 110, 43}, {111, 111, 48}, {112, 122, 43}, },
            {{48, 95, -16}, {97, 100, 43}, {101, 101, 49}, {102, 122, 43}, },
            {{48, 95, -16}, {97, 97, 50}, {98, 122, 43}, },
            {{48, 95, -16}, {97, 108, 43}, {109, 109, 51}, {110, 122, 43}, },
            {{48, 110, -20}, {111, 111, 52}, {112, 122, 43}, },
            {{48, 100, -21}, {101, 101, 53}, {102, 122, 43}, },
            {{48, 100, -21}, {101, 101, 54}, {102, 116, 43}, {117, 117, 55}, {118, 122, 43}, },
            {{48, 95, -16}, {97, 114, 43}, {115, 115, 56}, {116, 122, 43}, },
            {},
            {},
            {{9, 13, -8}, {32, 92, -3}, },
            {{9, 13, -6}, },
            {{9, 13, -5}, },
            {{9, 11, -5}, {13, 13, 57}, },
            {{9, 13, -5}, },
            {{9, 92, -4}, },
            {{9, 92, -30}, },
            {{9, 92, -30}, },
            {{10, 10, 58}, },
            {{32, 122, -9}, },
            {},
            {{32, 122, -9}, },
            {{32, 122, -9}, },
            {},
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{9, 92, -30}, },
            {{9, 92, -30}, },
            {{48, 101, -19}, {102, 102, 59}, {103, 122, 43}, },
            {{48, 95, -16}, {97, 115, 43}, {116, 116, 60}, {117, 122, 43}, },
            {{48, 108, -23}, {109, 109, 61}, {110, 122, 43}, },
            {{48, 114, -27}, {115, 115, 62}, {116, 116, 63}, {117, 122, 43}, },
            {{48, 95, -16}, {97, 104, 43}, {105, 105, 64}, {106, 122, 43}, },
            {{48, 95, -16}, {97, 111, 43}, {112, 112, 65}, {113, 122, 43}, },
            {{48, 95, -16}, {97, 99, 43}, {100, 100, 66}, {101, 116, 43}, {117, 117, 67}, {118, 122, 43}, },
            {{48, 99, -54}, {100, 100, 68}, {101, 111, 43}, {112, 112, 69}, {113, 122, 43}, },
            {{48, 95, -16}, {97, 113, 43}, {114, 114, 70}, {115, 122, 43}, },
            {{48, 95, -16}, {97, 98, 43}, {99, 99, 71}, {100, 122, 43}, },
            {{48, 100, -21}, {101, 101, 72}, {102, 122, 43}, },
            {{9, 13, -5}, },
            {{9, 92, -30}, },
            {{48, 100, -21}, {101, 101, 73}, {102, 122, 43}, },
            {{48, 95, -16}, {97, 97, 74}, {98, 122, 43}, },
            {{48, 111, -53}, {112, 112, 75}, {113, 122, 43}, },
            {{48, 98, -57}, {99, 99, 76}, {100, 122, 43}, },
            {{48, 100, -21}, {101, 101, 77}, {102, 122, 43}, },
            {{48, 95, -16}, {97, 107, 43}, {108, 108, 78}, {109, 122, 43}, },
            {{48, 107, -66}, {108, 108, 79}, {109, 122, 43}, },
            {{48, 100, -21}, {101, 101, 80}, {102, 122, 43}, },
            {{48, 114, -27}, {115, 115, 81}, {116, 122, 43}, },
            {{48, 95, -16}, {97, 116, 43}, {117, 117, 82}, {118, 122, 43}, },
            {{48, 107, -66}, {108, 108, 83}, {109, 122, 43}, },
            {{48, 95, -16}, {97, 117, 43}, {118, 118, 84}, {119, 122, 43}, },
            {{48, 98, -57}, {99, 99, 85}, {100, 122, 43}, },
            {{48, 114, -27}, {115, 115, 86}, {116, 122, 43}, },
            {{48, 98, -57}, {99, 99, 87}, {100, 122, 43}, },
            {{48, 98, -57}, {99, 99, 88}, {100, 122, 43}, },
            {{48, 110, -20}, {111, 111, 89}, {112, 122, 43}, },
            {{48, 113, -56}, {114, 114, 90}, {115, 122, 43}, },
            {{48, 98, -57}, {99, 99, 91}, {100, 122, 43}, },
            {{48, 116, -70}, {117, 117, 92}, {118, 122, 43}, },
            {{48, 100, -21}, {101, 101, 93}, {102, 122, 43}, },
            {{48, 115, -49}, {116, 116, 94}, {117, 122, 43}, },
            {{48, 100, -21}, {101, 101, 95}, {102, 122, 43}, },
            {{48, 95, -16}, {97, 109, 43}, {110, 110, 96}, {111, 122, 43}, },
            {{48, 104, -52}, {105, 105, 97}, {106, 122, 43}, },
            {{48, 104, -52}, {105, 105, 98}, {106, 122, 43}, },
            {{48, 100, -21}, {101, 101, 99}, {102, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 115, -49}, {116, 116, 100}, {117, 122, 43}, },
            {{48, 95, -16}, {97, 106, 43}, {107, 107, 101}, {108, 122, 43}, },
            {{48, 109, -84}, {110, 110, 102}, {111, 122, 43}, },
            {{48, 104, -52}, {105, 105, 103}, {106, 122, 43}, },
            {{48, 115, -49}, {116, 116, 104}, {117, 122, 43}, },
            {{48, 113, -56}, {114, 114, 105}, {115, 122, 43}, },
            {{48, 108, -23}, {109, 109, 106}, {110, 122, 43}, },
            {{48, 100, -21}, {101, 101, 107}, {102, 122, 43}, },
            {{48, 114, -27}, {115, 115, 108}, {116, 122, 43}, },
            {{48, 99, -54}, {100, 100, 109}, {101, 122, 43}, },
            {{48, 98, -57}, {99, 99, 110}, {100, 122, 43}, },
            {{48, 98, -57}, {99, 99, 111}, {100, 122, 43}, },
            {{48, 114, -27}, {115, 115, 112}, {116, 122, 43}, },
            {{48, 104, -52}, {105, 105, 113}, {106, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 100, -21}, {101, 101, 114}, {102, 122, 43}, },
            {{48, 111, -53}, {112, 112, 115}, {113, 122, 43}, },
            {{48, 114, -27}, {115, 115, 116}, {116, 122, 43}, },
            {{48, 100, -21}, {101, 101, 117}, {102, 122, 43}, },
            {{48, 100, -21}, {101, 101, 118}, {102, 122, 43}, },
            {{48, 98, -57}, {99, 99, 119}, {100, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 97, 120}, {98, 122, 43}, },
            {{48, 95, -16}, {97, 97, 121}, {98, 122, 43}, },
            {{48, 100, -21}, {101, 101, 122}, {102, 122, 43}, },
            {{48, 114, -27}, {115, 115, 123}, {116, 122, 43}, },
            {{48, 109, -84}, {110, 110, 124}, {111, 122, 43}, },
            {{48, 109, -84}, {110, 110, 125}, {111, 122, 43}, },
            {{48, 115, -49}, {116, 116, 126}, {117, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 109, -84}, {110, 110, 127}, {111, 122, 43}, },
            {{48, 115, -49}, {116, 116, 128}, {117, 122, 43}, },
            {{48, 109, -84}, {110, 110, 129}, {111, 122, 43}, },
            {{48, 115, -49}, {116, 116, 130}, {117, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 102, 43}, {103, 103, 131}, {104, 122, 43}, },
            {{48, 115, -49}, {116, 116, 132}, {117, 122, 43}, },
            {{48, 104, -52}, {105, 105, 133}, {106, 122, 43}, },
            {{48, 115, -49}, {116, 116, 134}, {117, 122, 43}, },
            {{48, 114, -27}, {115, 115, 135}, {116, 122, 43}, },
            {{48, 98, -57}, {99, 99, 136}, {100, 122, 43}, },
            {{48, 104, -52}, {105, 105, 137}, {106, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 110, -20}, {111, 111, 138}, {112, 122, 43}, },
            {{48, 100, -21}, {101, 101, 139}, {102, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 120, 43}, {121, 121, 140}, {122, 122, 43}, },
            {{48, 110, -20}, {111, 111, 141}, {112, 122, 43}, },
            {{48, 109, -84}, {110, 110, 142}, {111, 122, 43}, },
            {{48, 99, -54}, {100, 100, 143}, {101, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 109, -84}, {110, 110, 144}, {111, 122, 43}, },
            {{48, 122, -16}, },
            {{48, 57, 42}, {65, 65, 43}, {66, 66, 145}, {67, 90, 43}, {95, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 120, -138}, {121, 121, 146}, {122, 122, 43}, },
            {{48, 122, -16}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {26, 22, 22, 22, 22, 28, 23, -1, 20, 21, 18, 26, 26, 19, 24, 16, -1, 24, 24, 24, 24, 24, 24, 24, 24, 24, 14, 15, 27, 22, 22, 22, 22, 22, 27, 27, -1, -1, 25, -1, -1, 17, 24, 24, 27, 27, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 22, 27, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 5, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 6, 24, 24, 24, 24, 24, 24, 4, 24, 24, 24, 24, 24, 24, 24, 1, 10, 24, 24, 24, 24, 7, 13, 24, 24, 24, 24, 24, 24, 24, 3, 8, 24, 24, 0, 24, 24, 24, 24, 11, 24, 9, 24, 12, 24, 2, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
