/* This file was generated by SableCC (http://www.sablecc.org/). */

package bn.analysis.distribution.parser;

import bn.analysis.distribution.analysis.AnalysisAdapter;
import bn.analysis.distribution.node.EOF;
import bn.analysis.distribution.node.TDot;
import bn.analysis.distribution.node.TIdentifier;
import bn.analysis.distribution.node.TLBra;
import bn.analysis.distribution.node.TLPar;
import bn.analysis.distribution.node.TNcl;
import bn.analysis.distribution.node.TNoise;
import bn.analysis.distribution.node.TNumber;
import bn.analysis.distribution.node.TNumexp;
import bn.analysis.distribution.node.TP;
import bn.analysis.distribution.node.TPipe;
import bn.analysis.distribution.node.TProbabilityTok;
import bn.analysis.distribution.node.TQuote;
import bn.analysis.distribution.node.TRBra;
import bn.analysis.distribution.node.TRPar;
import bn.analysis.distribution.node.TSemi;
import bn.analysis.distribution.node.TSslash;
import bn.analysis.distribution.node.TTable;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTable(@SuppressWarnings("unused") TTable node)
    {
        this.index = 1;
    }

    @Override
    public void caseTProbabilityTok(@SuppressWarnings("unused") TProbabilityTok node)
    {
        this.index = 2;
    }

    @Override
    public void caseTSslash(@SuppressWarnings("unused") TSslash node)
    {
        this.index = 3;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 4;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 5;
    }

    @Override
    public void caseTNumexp(@SuppressWarnings("unused") TNumexp node)
    {
        this.index = 6;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 7;
    }

    @Override
    public void caseTQuote(@SuppressWarnings("unused") TQuote node)
    {
        this.index = 8;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 10;
    }

    @Override
    public void caseTLBra(@SuppressWarnings("unused") TLBra node)
    {
        this.index = 11;
    }

    @Override
    public void caseTRBra(@SuppressWarnings("unused") TRBra node)
    {
        this.index = 12;
    }

    @Override
    public void caseTP(@SuppressWarnings("unused") TP node)
    {
        this.index = 13;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 14;
    }

    @Override
    public void caseTNcl(@SuppressWarnings("unused") TNcl node)
    {
        this.index = 15;
    }

    @Override
    public void caseTNoise(@SuppressWarnings("unused") TNoise node)
    {
        this.index = 16;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 17;
    }
}
